#
# CircleCI configuration for salesforcedx-vscode-slds
#
#
version: 2.1

orbs:
  win: circleci/windows@2.2.0

commands:
  build-artifacts:
    description: 'Building and archiving extension artifacts.'
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v0-{{ checksum "package.json" }}
      - run: npm install
      - run:
          name: 'Compile in production mode'
          environment:
            - NODE_ENV: production
          command: |
            npm run compile
      - run:
          name: 'Packaging extensions'
          command: npm run vscode:package
      - run:
          name: 'Staging artifacts'
          command: |
            mkdir extensions
            find . -name "*.vsix" -type f -exec cp {} ./extensions \;
      - store_artifacts:
          path: ./extensions
      - save_cache:
          key: dependency-cache-v0-{{ checksum "package.json" }}
          paths:
            - node_modules

  build-win:
    description: 'Build for Windows.'
    steps:
      - run: git config --global core.autocrlf false
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-win3-{{ checksum "package.json" }}
            # if cache for exact version of 'package.json' is not present, then load the most recent cache
            - dependency-cache-win3-
      - run:
          name: 'Install node'
          shell: bash.exe
          command: |
            nvm install $NODE_VERSION
            nvm use $NODE_VERSION
            nvm install-latest-npm
      - run:
          name: 'Install dependent modules'
          shell: bash.exe
          command: |
            npm config set scripts-prepend-node-path true
            npm install
            npm install -g sfdx-cli@latest
            npm install -g codecov
            npm install -g junit-merge
      - run:
          name: 'Compile'
          shell: bash.exe
          command: npm run compile
      - save_cache:
          key: dependency-cache-win3-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: 'Run lint'
          shell: bash.exe
          command: |
            npm run lint

jobs:
  build-all:
    description: 'Build artifacts in a non-Windows environment'
    docker:
      - image: circleci/node:10.2.0
    environment:
      - SFDX_URL_LINUX: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
      - SFDX_AUTOUPDATE_DISABLE: true
      - SFDX_USE_GENERIC_UNIX_KEYCHAIN: true
      - SFDX_DOMAIN_RETRY: 300
    steps:
      - build-artifacts

  package-extension:
    description: 'Packages extenson in a Windows environment'
    executor: win/default
    environment:
      - SFDX_AUTOUPDATE_DISABLE: true
      - SFDX_DOMAIN_RETRY: 300
      - NODE_VERSION: '12.4.0'
    steps:
      - build-win
      - run:
          name: 'Packaging extension'
          shell: bash.exe
          command: |
            npm run vscode:package

workflows:
  version: 2.1

  # run a build on every commit
  commit-workflow:
    jobs:
      - build-all
      - package-extension
